### ISSUE TITLE
Share persistent link (include dots and image choice)

### ISSUE THREAD

**Issue by romsson** [LyonDataViz/occupapp#33] opened 2019-12-13 16:50 UTC
Create a url that contains positions and image choice. URL should be updated after each interaction so a page refresh re-loads exactly where the points were.

Eventually include/anticipate some more parameters (categories, etc.)

Eventually shorten the url (url limit is 2k chars)

**Comment by severo** [comment] 2019-12-13 18:04
Duplicate of https://github.com/LyonDataViz/occupapp/issues/32

**Closed by severo** 2019-12-13 18:04 UTC
